export type InstituicaoApoio = {
  id: number
  nome: string
  tipo: "Hospital" | "Associação" | "Centro Especializado"
  cidade: string
  estado: string
  telefone: string
  site: string
  lat: number
  lng: number
}

export const instituicoes: InstituicaoApoio[] = [
  {
    id: 1,
    nome: "Hospital das Clinicas de Sao Paulo",
    tipo: "Hospital",
    cidade: "Sao Paulo",
    estado: "SP",
    telefone: "(11) 2661-0000",
    site: "https://www.hc.fm.usp.br",
    lat: -23.5558,
    lng: -46.6697,
  },
  {
    id: 2,
    nome: "Instituto Nacional Fernandes Figueira",
    tipo: "Hospital",
    cidade: "Rio de Janeiro",
    estado: "RJ",
    telefone: "(21) 2554-1700",
    site: "https://www.iff.fiocruz.br",
    lat: -22.9083,
    lng: -43.1729,
  },
  {
    id: 3,
    nome: "Associacao Brasileira de Doencas Raras",
    tipo: "Associação",
    cidade: "Sao Paulo",
    estado: "SP",
    telefone: "(11) 3392-8090",
    site: "https://www.abdr.org.br",
    lat: -23.5616,
    lng: -46.6557,
  },
  {
    id: 4,
    nome: "Hospital de Clinicas de Porto Alegre",
    tipo: "Hospital",
    cidade: "Porto Alegre",
    estado: "RS",
    telefone: "(51) 3359-8000",
    site: "https://www.hcpa.edu.br",
    lat: -30.0368,
    lng: -51.2090,
  },
  {
    id: 5,
    nome: "Associacao dos Portadores de Fibrose Cistica",
    tipo: "Associação",
    cidade: "Sao Paulo",
    estado: "SP",
    telefone: "(11) 5572-5614",
    site: "https://www.fibrosecistica.org.br",
    lat: -23.5874,
    lng: -46.6576,
  },
  {
    id: 6,
    nome: "Hospital Universitario Walter Cantidio",
    tipo: "Centro Especializado",
    cidade: "Fortaleza",
    estado: "CE",
    telefone: "(85) 3366-8500",
    site: "https://www.huwc.ufc.br",
    lat: -3.7439,
    lng: -38.5434,
  },
  {
    id: 7,
    nome: "Instituto de Medicina Integral Fernando Figueira",
    tipo: "Centro Especializado",
    cidade: "Recife",
    estado: "PE",
    telefone: "(81) 2122-4100",
    site: "https://www.imip.org.br",
    lat: -8.0631,
    lng: -34.8711,
  },
  {
    id: 8,
    nome: "Associacao Brasileira de Esclerose Lateral Amiotrofica",
    tipo: "Associação",
    cidade: "Sao Paulo",
    estado: "SP",
    telefone: "(11) 5044-8900",
    site: "https://www.abrela.org.br",
    lat: -23.6012,
    lng: -46.6442,
  },
  {
    id: 9,
    nome: "Hospital de Clinicas da UNICAMP",
    tipo: "Hospital",
    cidade: "Campinas",
    estado: "SP",
    telefone: "(19) 3521-7000",
    site: "https://www.hc.unicamp.br",
    lat: -22.8214,
    lng: -47.0650,
  },
  {
    id: 10,
    nome: "Hospital das Clinicas da UFMG",
    tipo: "Hospital",
    cidade: "Belo Horizonte",
    estado: "MG",
    telefone: "(31) 3409-9000",
    site: "https://www.hc.ufmg.br",
    lat: -19.9245,
    lng: -43.9352,
  },
  {
    id: 11,
    nome: "Instituto de Genetica Medica",
    tipo: "Centro Especializado",
    cidade: "Curitiba",
    estado: "PR",
    telefone: "(41) 3360-1800",
    site: "https://www.hc.ufpr.br",
    lat: -25.4166,
    lng: -49.2653,
  },
  {
    id: 12,
    nome: "Associacao de Apoio a Mucoviscidose",
    tipo: "Associação",
    cidade: "Porto Alegre",
    estado: "RS",
    telefone: "(51) 3332-4788",
    site: "https://www.aamucoviscidose.org.br",
    lat: -30.0277,
    lng: -51.2287,
  },
  {
    id: 13,
    nome: "Hospital Universitario da USP",
    tipo: "Hospital",
    cidade: "Sao Paulo",
    estado: "SP",
    telefone: "(11) 3091-9200",
    site: "https://www.hu.usp.br",
    lat: -23.5613,
    lng: -46.7222,
  },
  {
    id: 14,
    nome: "Associacao Sindrome de Hunter Brasil",
    tipo: "Associação",
    cidade: "Sao Paulo",
    estado: "SP",
    telefone: "(11) 3266-4442",
    site: "https://www.hunterbrasil.org.br",
    lat: -23.5475,
    lng: -46.6361,
  },
  {
    id: 15,
    nome: "Centro de Referencia em Doencas Raras UFBA",
    tipo: "Centro Especializado",
    cidade: "Salvador",
    estado: "BA",
    telefone: "(71) 3283-8000",
    site: "https://www.hupes.ufba.br",
    lat: -12.9714,
    lng: -38.5014,
  },
  {
    id: 16,
    nome: "Hospital Infantil Joao Paulo II",
    tipo: "Hospital",
    cidade: "Belo Horizonte",
    estado: "MG",
    telefone: "(31) 3239-9200",
    site: "https://www.fhemig.mg.gov.br",
    lat: -19.9058,
    lng: -43.9384,
  },
  {
    id: 17,
    nome: "Associacao Brasileira de Sindrome de Marfan",
    tipo: "Associação",
    cidade: "Rio de Janeiro",
    estado: "RJ",
    telefone: "(21) 2579-0707",
    site: "https://www.marfan.org.br",
    lat: -22.9519,
    lng: -43.2105,
  },
  {
    id: 18,
    nome: "Centro de Referencia em Erros Inatos do Metabolismo",
    tipo: "Centro Especializado",
    cidade: "Sao Paulo",
    estado: "SP",
    telefone: "(11) 5576-4848",
    site: "https://www.unifesp.br",
    lat: -23.5996,
    lng: -46.6396,
  },
  {
    id: 19,
    nome: "Hospital Universitario de Brasilia",
    tipo: "Hospital",
    cidade: "Brasilia",
    estado: "DF",
    telefone: "(61) 3448-5600",
    site: "https://www.hub.unb.br",
    lat: -15.7638,
    lng: -47.8703,
  },
  {
    id: 20,
    nome: "Associacao Brasileira de Osteogenese Imperfeita",
    tipo: "Associação",
    cidade: "Sao Paulo",
    estado: "SP",
    telefone: "(11) 3392-6800",
    site: "https://www.aboi.org.br",
    lat: -23.5489,
    lng: -46.6388,
  },
]